# Generated by Django 4.2 on 2024-01-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0003_askinformation_content_askinformation_reg_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="askinformation",
            name="respond_content",
            field=models.TextField(default=""),
        ),
    ]
