# Generated by Django 4.2 on 2024-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0004_askinformation_respond_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="askinformation",
            name="email",
            field=models.EmailField(default="<Email>", max_length=200),
        ),
        migrations.AddField(
            model_name="askinformation",
            name="name",
            field=models.CharField(default="익명", max_length=100),
        ),
    ]
