# Generated by Django 4.2 on 2024-01-11 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0005_askinformation_email_askinformation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="askinformation",
            name="reg_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
