# Generated by Django 4.2 on 2024-01-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0006_alter_askinformation_reg_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="askinformation",
            name="reg_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
