# Generated by Django 4.2 on 2024-01-16 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0008_alter_askinformation_options_alter_faq_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="askinformation",
            options={"verbose_name": "1:1 문의", "verbose_name_plural": "1:1 문의"},
        ),
    ]
