# Generated by Django 4.2 on 2024-01-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_recommendmarkup_reservationuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationConstraint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("OPEN", "영업 시간"), ("CLOSED", "영업 종료")],
                        default="OPEN",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "예약 제약",
                "verbose_name_plural": "예약 제약",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "예약 완료"),
                            ("WAITTING", "예약 대기"),
                            ("CANCELLED", "예약 취소"),
                        ],
                        default="WAITTING",
                        max_length=50,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "간단 진단"),
                            ("BASIC", "기본 진단"),
                            ("BODY", "골격 진단"),
                            ("PRO", "프로 진단"),
                        ],
                        default="SIMPLE",
                        max_length=50,
                    ),
                ),
                ("reservation_many", models.IntegerField(default=1)),
                ("reservation_date", models.DateField()),
                ("reservation_hour", models.BigIntegerField()),
                ("reservation_min", models.BigIntegerField()),
                ("reg_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.reservationuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약 관리",
                "verbose_name_plural": "예약 관리",
            },
        ),
    ]
