# Generated by Django 4.2 on 2024-01-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.CharField(max_length=200),
        ),
    ]
